# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CodableMvvmUnitTestPractice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod "ViewAnimator"

  # Pods for CodableMvvmUnitTestPractice

  target 'CodableMvvmUnitTestPracticeTests' do
    inherit! :search_paths
    # Pods for testing  

  end

end
